// Generated by uniffi-bindgen-react-native
#include "react-native-rust-ffi.h"
#include "generated/rust_ffi.hpp"

namespace rustffi {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeRustFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}