// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-rust-ffi.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNRustFFIReactNativeSpec.h"

@interface RustFfi : NSObject <NativeRustFfiSpec>
#else
#import <React/RCTBridgeModule.h>

@interface RustFfi : NSObject <RCTBridgeModule>
#endif

@end